### ISSUE TITLE
refresh_tokens are resuable?

### ISSUE THREAD

**Issue by Pjort** [authorizerdev/docs#20] opened 2022-11-02 22:27 UTC
I want to ask something about refresh_tokens. I assumed the behaviour was that a refresh_token only could be used once, and I do get a 401 reponse, when using the same refresh_token twice, with a message of:
{
    "error": "unauthorized",
    "error_description": "unauthorized"
}
But I also get a full set of tokens:
{
    "access_token": "aaaa.aaaa.aaaa",
    "expires_in": 1800,
    "id_token": "aaaa.aaaa.aaaa",
    "refresh_token": "aaaa.aaaa.aaaa",
    "roles": [
        "user"
    ],
    "scope": [
        "offline_access"
    ]
}

Is this normal behaviour? Since in my mind it defeats the purpose of a refresh token if it can be used multiple times...

**Comment by lakhansamani** [comment] 2022-11-03 09:32
@Pjort refresh token can be used get new access token & id tokens
For security reasons we rotate refresh token with every request, so that if your older refresh token was exposed by any chance your data is safe.

Here is an example of it: https://github.com/authorizerdev/examples/blob/main/with-react-native-expo/App.js#L50

**Comment by Pjort** [comment] 2022-11-03 09:50
> @Pjort refresh token can be used get new access token & id tokens For security reasons we rotate refresh token with every request, so that if your older refresh token was exposed by any chance your data is safe.
> 
> Here is an example of it: https://github.com/authorizerdev/examples/blob/main/with-react-native-expo/App.js#L50

From what you are saying it sounds like you should NOT be able to use a refresh token more than once? From testing on latest build I find I am actually able to use it multiple times though...

**Comment by lakhansamani** [comment] 2022-11-03 14:33
With what apis you are using it for multiple times?

**Comment by lakhansamani** [comment] 2022-11-03 14:44
Released as part of 1.1.24
Soon will be out: https://github.com/authorizerdev/authorizer/actions/runs/3386649746/jobs/5626324800

Though disclaimer I am working on fixing OpenID standard: https://github.com/authorizerdev/authorizer/pull/270

**Comment by Pjort** [comment] 2022-11-03 15:30
Okay, that did actually fix the problem with being able to resuse the same refresh_token over and over again. But now the new refresh token isn't valid, I guess the new refresh token doesn't get put in the memory/db?

**Comment by lakhansamani** [comment] 2022-11-03 19:45
I am able to reproduce it and I have also found the root cause of it.
I will work on the solution later tomorrow.

Thanks

**Comment by lakhansamani** [comment] 2022-11-04 05:15
@Pjort I have fixed this tested on our react-native expo and released it as part of 1.1.25

**Closed by lakhansamani** 2022-11-04 05:15 UTC
